on: [push, pull_request]
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go build -ldflags "-X main.version=$(git log -1 --pretty=%h)"
      - run: ./pan-bot -v
      - uses: golangci/golangci-lint-action@v3
        with:
          args: -E goimports
