name: Build and lint

on: [pull_request, workflow_dispatch]
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: Build
        run: go build -ldflags "-X main.version=$(git log -1 --pretty=%h)" -v
        run: ./pan-bot -v

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
